services:
  mongodb:
    image: mongo:7
    container_name: hackathon_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hackathon_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - hackathon_network

volumes:
  mongodb_data:
    driver: local

networks:
  hackathon_network:
    driver: bridge
